forge-1.16.5:
  gradle: |
    repositories {
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
    dependencies {
       compileOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641085")
       runtimeOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641085")
    }
  update_files:
    - ~
forge-1.17.1:
  gradle: |
    repositories {
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
    dependencies {
       compileOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641135")
       runtimeOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641135")
    }
  update_files:
    - ~
forge-1.18.1:
  gradle: |
    repositories {
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
    dependencies {
       compileOnly fg.deobf("curse.maven:cloth-config-forge-348521:3608026")
       runtimeOnly fg.deobf("curse.maven:cloth-config-forge-348521:3608026")
    }
  update_files:
    - ~
forge-1.18.2:
  gradle: |
    repositories {
        maven {
            url "https://www.cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }
    dependencies {
       compileOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641133")
       runtimeOnly fg.deobf("curse.maven:cloth-config-forge-348521:3641133")
    }
  update_files:
    - ~
name: "Cloth Config"